# Jekyll 설정
title: "스프린트 미션 보관함"
description: "코드잇 AI 4기 스프린트 미션 결과물 보관함"
url: "https://c0z0c.github.io"
baseurl: "/sprint_mission"

# Build 설정
markdown: kramdown
highlighter: rouge
# incremental: true               # GitHub Pages에서는 지원하지 않음, 제거

kramdown:
  input: GFM                    # GitHub Flavored Markdown 사용
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false         # GitHub Pages 호환성을 위해 false로 변경
    block:
      line_numbers: false
    css_class: 'highlight'
  math_engine: mathjax
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  parse_span_html: true

# MathJax 설정
mathjax: true

# Mermaid 다이어그램 지원
mermaid: true
  
# GitHub Pages 호환 플러그인만 사용
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-redirect-from
  - jekyll-mentions

# 페이지네이션 설정
paginate: 10
paginate_path: "/page:num/"

# 파일 처리
include:
  - "_pages"
  - ".htaccess"

# 제외할 파일들
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - LICENSE
  - CHANGELOG.md
  - .sass-cache/
  - .jekyll-cache/
  - "helper_c0z0c_dev.py"

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_date: true
      author: true
  - scope:
      path: "스프린트미션_완료"
    values:
      layout: "default"
      sitemap: true

# 한국어 설정
lang: ko-KR
timezone: Asia/Seoul

# 인코딩 설정
encoding: utf-8

# SEO 최적화
author:
  name: "c0z0c"
  email: "c0z0c@hotmail.com"

social:
  name: "c0z0c"
  links:
    - "https://github.com/c0z0c"

# GitHub Pages 설정
github: [metadata]
repository: c0z0c/sprint_mission
branch: main

safe: true
lsi: false

# 성능 최적화
liquid:
  error_mode: warn              # strict에서 warn으로 변경
  strict_filters: false         # false로 변경
  strict_variables: false       # false로 변경

# 컬렉션 설정
collections:
  missions:
    output: true
    permalink: /missions/:name/

# SASS 설정
sass:
  style: compressed
  sass_dir: _sass
  
# 캐싱 설정
future: false
show_drafts: false
limit_posts: 0

# RSS Feed 설정
feed:
  posts_limit: 20
  excerpt_only: true