"""
설정 및 상수 정의
"""

# API 설정
API_URL = "http://34.64.206.210:8080/predictions/sdxl"

# 한글-영문 프롬프트 매핑 딕셔너리
PROMPT_CATEGORIES = {
    "피사체": {
        "10대 후반 여성": "a beautiful teenage girl, late teens",
        "20대 초반 여성": "a beautiful young woman in her early 20s",
        "20대 후반 여성": "a woman in her late 20s",
        "30대 여성": "a woman in her 30s",
        "10대 후반 남성": "a teenage boy, late teens",
        "20대 초반 남성": "a handsome young man in his early 20s",
        "20대 후반 남성": "a man in his late 20s",
        "30대 남성": "a man in his 30s",
        "중년 남성": "a middle-aged man",
        "중년 여성": "a middle-aged woman",
        "어린이": "a child",
        "노인": "an elderly person",
        "비즈니스맨": "a businessman",
        "비즈니스우먼": "a businesswoman",
        "학생": "a student",
        "커플": "a couple",
        "가족": "a family",
        "고양이": "a cat",
        "강아지": "a dog",
        "말": "a horse",
        "용": "a dragon",
        "유니콘": "a unicorn",
        "새": "a bird",
        "물고기": "a fish",
        "꽃": "flowers",
        "나무": "a tree",
        "산": "mountains",
        "집": "a house",
        "성": "a castle",
        "우주선": "a spaceship",
        "자동차": "a car",
        "로봇": "a robot",
        "천사": "an angel",
    },
    "인종/민족": {
        "한국인": "Korean",
        "동양인 (일반)": "East Asian",
        "중국인": "Chinese",
        "일본인": "Japanese",
        "동남아시아인": "Southeast Asian",
        "백인 (유럽계)": "Caucasian, European",
        "백인 (미국)": "White American",
        "흑인 (아프리카계)": "African, Black",
        "흑인 (미국)": "African American",
        "라틴계": "Latino, Hispanic",
        "중동계": "Middle Eastern",
        "인도계": "Indian, South Asian",
        "혼혈": "mixed race, multiracial",
    },
    "인물 스타일": {
        "K-POP 스타": "K-pop idol, Korean pop star style",
        "K-드라마 배우": "Korean drama actor style",
        "할리우드 스타": "Hollywood celebrity style",
        "패션 모델": "fashion model",
        "슈퍼모델": "supermodel",
        "인플루언서": "social media influencer",
        "아이돌": "idol, pop star",
        "뮤지션": "musician, artist",
        "운동선수": "athlete, sporty",
        "댄서": "professional dancer",
        "배우": "actor, actress",
        "아티스트": "creative artist",
    },
    "스타일": {
        "사실적인": "photorealistic",
        "판타지": "fantasy art",
        "애니메이션": "anime style",
        "만화": "cartoon style",
        "수채화": "watercolor painting",
        "유화": "oil painting",
        "3D 렌더링": "3D render",
        "미니멀": "minimalist",
        "사이버펑크": "cyberpunk",
        "스팀펑크": "steampunk",
        "복고풍": "retro style",
        "미래적": "futuristic",
        "바로크": "baroque style",
        "인상주의": "impressionist",
        "추상화": "abstract art",
    },
    "배경/장소": {
        "자연": "natural scenery",
        "해변": "beach",
        "강가": "riverside, by the river",
        "호숫가": "lakeside",
        "숲": "forest",
        "사막": "desert",
        "산": "mountains",
        "눈 덮인 산": "snowy mountains",
        "공원": "park",
        "정원": "garden",
        "도시": "city background",
        "거리": "street scene, urban street",
        "도심": "downtown, city center",
        "골목길": "alleyway",
        "카페": "cafe, coffee shop",
        "레스토랑": "restaurant",
        "바": "bar",
        "사무실": "office",
        "회의실": "conference room",
        "세미나실": "seminar room",
        "강의실": "lecture hall, classroom",
        "도서관": "library",
        "병원": "hospital",
        "병원 로비": "hospital lobby",
        "진료실": "medical examination room",
        "호텔 로비": "hotel lobby",
        "호텔 객실": "hotel room",
        "쇼핑몰": "shopping mall",
        "백화점": "department store",
        "공항": "airport",
        "기차역": "train station",
        "체육관": "gym, fitness center",
        "스튜디오": "studio",
        "갤러리": "art gallery",
        "박물관": "museum",
        "극장": "theater",
        "콘서트홀": "concert hall",
        "학교": "school",
        "대학 캠퍼스": "university campus",
        "우주": "space background",
        "동굴": "cave",
        "수중": "underwater",
        "하늘": "sky",
        "구름": "clouds",
        "별이 빛나는 밤": "starry night",
        "일몰": "sunset",
        "일출": "sunrise",
        "밤": "night scene",
        "옥상": "rooftop",
    },
    "조명": {
        "자연광": "natural lighting",
        "극적인 조명": "dramatic lighting",
        "부드러운 조명": "soft lighting",
        "네온": "neon lighting",
        "역광": "backlighting",
        "황금 시간대": "golden hour",
        "파란 시간대": "blue hour",
        "스튜디오 조명": "studio lighting",
        "영화 같은 조명": "cinematic lighting",
        "빛나는": "glowing",
        "어두운": "dark moody lighting",
    },
    "품질/효과": {
        "초상세한": "highly detailed",
        "8K": "8k resolution",
        "4K": "4k resolution",
        "선명한": "sharp focus",
        "걸작": "masterpiece",
        "최고 품질": "best quality",
        "전문가 수준": "professional",
        "영화 같은": "cinematic",
        "생동감 있는": "vibrant colors",
        "대비 높은": "high contrast",
        "HDR": "HDR",
        "초현실적": "hyperrealistic",
    },
}
